# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ledger.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ledger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cledger.proto\x12\x06ledger\"%\n\x0fReceiptsRequest\x12\x12\n\nimage_data\x18\x01 \x03(\x0c\"\'\n\x10ReceiptsResponse\x12\x13\n\x0bjson_output\x18\x01 \x01(\t2U\n\rLedgerService\x12\x44\n\x0fProcessReceipts\x12\x17.ledger.ReceiptsRequest\x1a\x18.ledger.ReceiptsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ledger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIPTSREQUEST']._serialized_start=24
  _globals['_RECEIPTSREQUEST']._serialized_end=61
  _globals['_RECEIPTSRESPONSE']._serialized_start=63
  _globals['_RECEIPTSRESPONSE']._serialized_end=102
  _globals['_LEDGERSERVICE']._serialized_start=104
  _globals['_LEDGERSERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
