# dev 브랜치에 기본 CI 워크플로우 설정: 코드의 빌드와 테스트를 자동화하여 코드의 안정성을 확보
# 코드 검증 후 main 브랜치로 머지하기 위함(dev 브랜치에서 문제가 없는 코드를 main 브랜치로 머지)

name: Dev CI Workflow

on:
  push:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set environment variable
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Create prompt_config.yaml
        run: |
          mkdir -p image_to_text_description
          echo "prompts:\n  system_prompt: Test system prompt\n  user_prompt: Test user prompt" > image_to_text_description/prompt_config.yaml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest --maxfail=3 --disable-warnings
